apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: hellgrenj/projects:sagas.payment.v2
        name: payment
        resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
