apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: payment
        name: payment
        env:
        - name: SIMULATED_DELAY 
          valueFrom:
            configMapKeyRef:
              name: config        
              key: delay_ms
        resources: {}
      restartPolicy: Always
status: {}
