apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: paymentdata
  name: paymentdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentdb
  name: paymentdb
spec:
  ports:
    - name: "paymentdb"
      port: 27017
      targetPort: 27017
  selector:
    app: paymentdb
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paymentdb
  name: paymentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paymentdb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd
          image: mongo:5.0.5
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: paymentdata
      restartPolicy: Always
      volumes:
        - name: paymentdata
          persistentVolumeClaim:
            claimName: paymentdata
status: {}
