apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warehouse
  name: warehouse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse
  strategy: {}
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      initContainers: # <-- init container that waits for migration job to be finished before starting main container 
      - name: "wait-for-warehouse-db-mig"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: ""
        args: 
        - "job"
        - "warehouse-db-mig"
      containers:
      - image: warehouse
        name: warehouse
        resources: {}
      restartPolicy: Always
status: {}
